### ISSUE TITLE
En tant que RQSE je veux pouvoir définir un autre type de question que SAMI afin de récolter toutes les données nécessaires

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/controle#21]
**Brief**
Ajouter le support des types de réponses suivants :

- boolean (vrais ou faux)
- text
- float (nombre flotant)
- integer (nombre entier)
- textarea (texte long)
- date
- datetime

**Comment by killiankopp** [comment]
**Roles**
- design team :  
- dev team :

**Comment by killiankopp** [comment]
**Todo**
- [ ] @ :
