### ISSUE TITLE
En tant que contrôleur, je veux voir un message s'il n'y aucune programmation en cours afin de m'assurer que le logiciel ne bug pas

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/controle#49]
Afficher "0 résultat" lorsqu'il n'y a pas de données dans Programmation et Consultation

![Screenshot from 2023-01-13 11-04-39](https://user-images.githubusercontent.com/945411/212293442-c516ced8-c7b2-4af4-83cb-c9e418887ad4.png)
![Screenshot from 2023-01-13 11-04-39](https://user-images.githubusercontent.com/945411/212293474-3e2966d4-a8de-4267-a903-99af408e2801.png)

**Comment by marilehoux** [comment]
ok pour programmation
in progress sur consultation

**Comment by marilehoux** [comment]
![image](https://user-images.githubusercontent.com/88326618/225877383-1b2ddf14-5c7b-4795-8ada-bd0546d8ed66.png)
